/**
 * Example E2E Test Using Seeded Data
 *
 * Demonstrates how to use the test database seeding infrastructure
 * to run tests without real Ring API access.
 *
 * Generated by ORCH-3: Create Test Database Seeding
 */

import { test, expect } from '@playwright/test';
import { setupApiMocks, getSeedData } from '../../setup/mock-api';

test.describe('Seeded Data Examples', () => {
  test.describe('Using API Mocks', () => {
    test('should display seeded devices on dashboard', async ({ page }) => {
      // Setup API mocks before navigation
      await setupApiMocks(page);

      // Navigate to dashboard
      await page.goto('/');

      // Wait for content to load
      await page.waitForSelector('[data-testid="camera-card"]', { timeout: 10000 });

      // Get seed data for assertions
      const seedData = getSeedData();

      // Verify correct number of devices displayed
      const cameraCards = page.locator('[data-testid="camera-card"]');
      const count = await cameraCards.count();

      expect(count).toBe(seedData.devices.length);
      console.log(`✓ Displayed ${count} devices from seed data`);
    });

    test('should show low battery warning for seeded low-battery camera', async ({ page }) => {
      await setupApiMocks(page);
      await page.goto('/');

      // Backyard Camera has 15% battery (low)
      const lowBatteryCamera = page.locator('[data-testid="camera-card"]').filter({
        hasText: 'Backyard Camera',
      });

      // Check for low battery warning
      const warning = lowBatteryCamera.locator('[data-testid="low-battery-warning"]');
      await expect(warning).toBeVisible();
      console.log('✓ Low battery warning displayed for 15% battery camera');
    });

    test('should show offline status for seeded offline camera', async ({ page }) => {
      await setupApiMocks(page);
      await page.goto('/');

      // Living Room Camera is offline
      const offlineCamera = page.locator('[data-testid="camera-card"]').filter({
        hasText: 'Living Room Camera',
      });

      // Check for offline status
      const status = offlineCamera.locator('[data-testid="status-indicator"]');
      await expect(status).toHaveAttribute('data-status', 'offline');
      console.log('✓ Offline status displayed for offline camera');
    });

    test('should display seeded events', async ({ page }) => {
      await setupApiMocks(page);
      await page.goto('/events');

      // Wait for events to load
      await page.waitForSelector('[data-testid="event-item"]', { timeout: 10000 });

      // Get seed data
      const seedData = getSeedData();

      // Verify events are displayed
      const events = page.locator('[data-testid="event-item"]');
      const count = await events.count();

      expect(count).toBeGreaterThan(0);
      expect(count).toBeLessThanOrEqual(seedData.events.length);
      console.log(`✓ Displayed ${count} events from seed data`);
    });

    test('should show seeded recordings count', async ({ page }) => {
      await setupApiMocks(page);
      await page.goto('/');

      const seedData = getSeedData();

      // Wait for stats to load
      await page.waitForSelector('[data-testid="recordings-count"]', { timeout: 10000 });

      // Check recordings count matches seed data
      const recordingsCount = page.locator('[data-testid="recordings-count"]');
      await expect(recordingsCount).toContainText(seedData.stats.totalRecordings.toString());
      console.log(`✓ Recordings count: ${seedData.stats.totalRecordings}`);
    });
  });

  test.describe('Seed Data Validation', () => {
    test('seed data meets acceptance criteria', async () => {
      const seedData = getSeedData();

      // Verify acceptance criteria
      expect(seedData.devices.length).toBeGreaterThanOrEqual(3);
      console.log(`✓ Has ${seedData.devices.length} devices (requirement: 3+)`);

      expect(seedData.events.length).toBeGreaterThanOrEqual(10);
      console.log(`✓ Has ${seedData.events.length} events (requirement: 10+)`);

      expect(seedData.recordings.length).toBeGreaterThan(0);
      console.log(`✓ Has ${seedData.recordings.length} recordings`);

      expect(seedData.zones.length).toBeGreaterThan(0);
      console.log(`✓ Has ${seedData.zones.length} zone configurations`);
    });

    test('seed data has expected device states', async () => {
      const seedData = getSeedData();

      // Find specific devices
      const frontDoor = seedData.devices.find(d => d.id === 'test-camera-1');
      const backyard = seedData.devices.find(d => d.id === 'test-camera-2');
      const livingRoom = seedData.devices.find(d => d.id === 'test-camera-3');

      // Verify Front Door Camera (online, good battery)
      expect(frontDoor).toBeDefined();
      expect(frontDoor?.isOnline).toBe(true);
      expect(frontDoor?.batteryLevel).toBe(85);
      console.log('✓ Front Door Camera: online, 85% battery');

      // Verify Backyard Camera (online, low battery)
      expect(backyard).toBeDefined();
      expect(backyard?.isOnline).toBe(true);
      expect(backyard?.batteryLevel).toBe(15);
      console.log('✓ Backyard Camera: online, 15% battery (LOW)');

      // Verify Living Room Camera (offline)
      expect(livingRoom).toBeDefined();
      expect(livingRoom?.isOnline).toBe(false);
      expect(livingRoom?.batteryLevel).toBe(50);
      console.log('✓ Living Room Camera: OFFLINE, 50% battery');
    });

    test('seed data has events with recordings', async () => {
      const seedData = getSeedData();

      // Count events with recordings
      const eventsWithRecordings = seedData.events.filter(e => e.recordingId);
      expect(eventsWithRecordings.length).toBeGreaterThan(0);
      console.log(`✓ ${eventsWithRecordings.length} events have associated recordings`);

      // Verify recordings reference valid events
      for (const recording of seedData.recordings) {
        const event = seedData.events.find(e => e.id === recording.eventId);
        expect(event).toBeDefined();
      }
      console.log(`✓ All ${seedData.recordings.length} recordings reference valid events`);
    });

    test('seed data has zone configurations', async () => {
      const seedData = getSeedData();

      // Verify zones exist
      expect(seedData.zones.length).toBeGreaterThan(0);

      // Verify zone structure
      for (const zone of seedData.zones) {
        expect(zone.name).toBeDefined();
        expect(zone.triggerCameras).toBeDefined();
        expect(zone.recordCameras).toBeDefined();
        expect(zone.motionCooldownSeconds).toBeGreaterThan(0);
        console.log(`✓ Zone "${zone.name}": ${zone.triggerCameras.length} triggers, ${zone.recordCameras.length} recorders`);
      }
    });
  });

  test.describe('Configuration Validation', () => {
    test('system config has battery optimization settings', async ({ page }) => {
      await setupApiMocks(page);

      const response = await page.request.get('/api/system/config');
      const config = await response.json();

      // Verify battery-optimized defaults
      expect(config.ringPollingIntervalSeconds).toBeGreaterThanOrEqual(30);
      expect(config.recordingDurationSeconds).toBeLessThanOrEqual(30);
      expect(config.bufferEnabled).toBe(false);

      console.log('✓ Battery optimization config validated');
      console.log(`  - Polling interval: ${config.ringPollingIntervalSeconds}s`);
      console.log(`  - Recording duration: ${config.recordingDurationSeconds}s`);
      console.log(`  - Buffer enabled: ${config.bufferEnabled}`);
    });
  });
});

// Example: Testing without API mocks (using real database)
test.describe('Direct Database Access', () => {
  test('can query seeded database directly', async () => {
    // Note: This test accesses the database directly
    // Most tests should use API mocks instead
    const Database = (await import('better-sqlite3')).default;
    const db = new Database('./data/test-ring-security.db');

    const devices = db.prepare('SELECT COUNT(*) as count FROM devices').get() as { count: number };
    const events = db.prepare('SELECT COUNT(*) as count FROM events').get() as { count: number };
    const recordings = db.prepare('SELECT COUNT(*) as count FROM recordings').get() as { count: number };

    expect(devices.count).toBeGreaterThanOrEqual(3);
    expect(events.count).toBeGreaterThanOrEqual(10);
    expect(recordings.count).toBeGreaterThan(0);

    console.log('✓ Database seeded successfully:');
    console.log(`  - ${devices.count} devices`);
    console.log(`  - ${events.count} events`);
    console.log(`  - ${recordings.count} recordings`);

    db.close();
  });
});
